kind: Deployment
apiVersion: apps/v1
metadata:
  name: alicloud-clickhouse-autopause
  labels:
    app.kubernetes.io/name: alicloud-clickhouse-autopause
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alicloud-clickhouse-autopause
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alicloud-clickhouse-autopause
    spec:
      containers:
        - name: alicloud-clickhouse-autopause
          image: zhangbc/alicloud-clickhouse-autopause:0.0.1
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "sleep 5"
          resources:
            limits:
              cpu: "500m"
              memory: 1024Mi
            requests:
              cpu: "100m"
              memory: 256Mi
          ports:
            - containerPort: 80
              protocol: TCP
              name: grpc
          imagePullPolicy: Always
          volumeMounts:
            - name: alicloud-clickhouse-autopause
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            tcpSocket:
              port: grpc
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 3
            periodSeconds: 10
            tcpSocket:
              port: grpc
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 3
            periodSeconds: 10
            tcpSocket:
              port: grpc
      volumes:
        - name: alicloud-clickhouse-autopause
          configMap:
            name: alicloud-clickhouse-autopause
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
