apiVersion: v1
kind: Service
metadata:
  name: alicloud-clickhouse-autopause
spec:
  selector:
    app.kubernetes.io/name: alicloud-clickhouse-autopause
  ports:
    - port: 80
      targetPort: grpc
